### PR TITLE
issue #33 made dropping animation 

### PR DESCRIPTION
**Pull request by YooAshu**
fixed issue #33 

Screenshot (83)

### CODE REVIEW

**Comment by ASHISH26940** [comment]
Could you add text and images on hover just like the original website then I am changing the difficulty to hard.

**Comment by YooAshu** [comment]
Yeah I can do that

**Comment by ASHISH26940** [comment]
Then do it. Best of luck

**Comment by ASHISH26940** [comment]
Also add some animation on the entry of text and images

**Comment by YooAshu** [comment]
@ASHISH26940 plss check the changes

**Comment by YooAshu** [comment]
and also pls assign me for the navbar issue,
As I said I will add animation like the original website

**Comment by ASHISH26940** [comment]
## Lastly add zoom effect on hover here.
image

Just do it as the last issue in this PR.

## Also mention the Issue of the navbar

**Comment by YooAshu** [comment]
issue #44

**Comment by ASHISH26940** [comment]
I will assign not assign navbar issue since someone else has been working on it.

**Comment by ASHISH26940** [comment]
Yeah you can do the navbar issue then comment there Assign me

**Pull request merged**
