### PR TITLE
Beautiful Image Hover Effect

### PR DESCRIPTION
**Pull request by rko0211**
Please review my PR

Resolve issue : #49

### CODE REVIEW

**Comment by ASHISH26940** [comment]
@rko0211  Please change the color of hover. The combination is not beautiful and its too sharp . Plus I thought after seeing the ScreenShot that you were doing changes only of dark mode

**Comment by rko0211** [comment]
OK i will change it only for dark mode

**Comment by rko0211** [comment]
Kindly check it i have changed hover effect.

**Comment by ASHISH26940** [comment]
Ok good merging it.

**Comment by rko0211** [comment]
> Ok good merging it.

Thank you

**Pull request merged**
